// Generated by gencpp from file xj_robot_pnc/exe_pathRequest.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_EXE_PATHREQUEST_H
#define XJ_ROBOT_PNC_MESSAGE_EXE_PATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xj_robot_pnc
{
template <class ContainerAllocator>
struct exe_pathRequest_
{
  typedef exe_pathRequest_<ContainerAllocator> Type;

  exe_pathRequest_()
    : command(0)
    , path_name()
    , dir()  {
    }
  exe_pathRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , path_name(_alloc)
    , dir(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_name_type;
  _path_name_type path_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dir_type;
  _dir_type dir;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif

  enum {
    START = 0u,
    STOP = 1u,
    PAUSE = 2u,
  };


  typedef boost::shared_ptr< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct exe_pathRequest_

typedef ::xj_robot_pnc::exe_pathRequest_<std::allocator<void> > exe_pathRequest;

typedef boost::shared_ptr< ::xj_robot_pnc::exe_pathRequest > exe_pathRequestPtr;
typedef boost::shared_ptr< ::xj_robot_pnc::exe_pathRequest const> exe_pathRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator1> & lhs, const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.path_name == rhs.path_name &&
    lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator1> & lhs, const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xj_robot_pnc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "547e8a352319040fe2a40865ad6349c2";
  }

  static const char* value(const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x547e8a352319040fULL;
  static const uint64_t static_value2 = 0xe2a40865ad6349c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xj_robot_pnc/exe_pathRequest";
  }

  static const char* value(const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 START = 0\n"
"uint8 STOP = 1\n"
"uint8 PAUSE = 2\n"
"\n"
"uint8 command\n"
"string path_name\n"
"string dir\n"
;
  }

  static const char* value(const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.path_name);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct exe_pathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xj_robot_pnc::exe_pathRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "path_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path_name);
    s << indent << "dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_EXE_PATHREQUEST_H
