// Generated by gencpp from file xj_robot_pnc/exe_path.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_EXE_PATH_H
#define XJ_ROBOT_PNC_MESSAGE_EXE_PATH_H

#include <ros/service_traits.h>


#include <xj_robot_pnc/exe_pathRequest.h>
#include <xj_robot_pnc/exe_pathResponse.h>


namespace xj_robot_pnc
{

struct exe_path
{

typedef exe_pathRequest Request;
typedef exe_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct exe_path
} // namespace xj_robot_pnc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xj_robot_pnc::exe_path > {
  static const char* value()
  {
    return "05ccd160c52332199029116636e3083a";
  }

  static const char* value(const ::xj_robot_pnc::exe_path&) { return value(); }
};

template<>
struct DataType< ::xj_robot_pnc::exe_path > {
  static const char* value()
  {
    return "xj_robot_pnc/exe_path";
  }

  static const char* value(const ::xj_robot_pnc::exe_path&) { return value(); }
};


// service_traits::MD5Sum< ::xj_robot_pnc::exe_pathRequest> should match
// service_traits::MD5Sum< ::xj_robot_pnc::exe_path >
template<>
struct MD5Sum< ::xj_robot_pnc::exe_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::exe_path >::value();
  }
  static const char* value(const ::xj_robot_pnc::exe_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::exe_pathRequest> should match
// service_traits::DataType< ::xj_robot_pnc::exe_path >
template<>
struct DataType< ::xj_robot_pnc::exe_pathRequest>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::exe_path >::value();
  }
  static const char* value(const ::xj_robot_pnc::exe_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xj_robot_pnc::exe_pathResponse> should match
// service_traits::MD5Sum< ::xj_robot_pnc::exe_path >
template<>
struct MD5Sum< ::xj_robot_pnc::exe_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::exe_path >::value();
  }
  static const char* value(const ::xj_robot_pnc::exe_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::exe_pathResponse> should match
// service_traits::DataType< ::xj_robot_pnc::exe_path >
template<>
struct DataType< ::xj_robot_pnc::exe_pathResponse>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::exe_path >::value();
  }
  static const char* value(const ::xj_robot_pnc::exe_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_EXE_PATH_H
