// Generated by gencpp from file xj_robot_pnc/nav_goal.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_NAV_GOAL_H
#define XJ_ROBOT_PNC_MESSAGE_NAV_GOAL_H

#include <ros/service_traits.h>


#include <xj_robot_pnc/nav_goalRequest.h>
#include <xj_robot_pnc/nav_goalResponse.h>


namespace xj_robot_pnc
{

struct nav_goal
{

typedef nav_goalRequest Request;
typedef nav_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_goal
} // namespace xj_robot_pnc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xj_robot_pnc::nav_goal > {
  static const char* value()
  {
    return "5776176c95d37b90d51191fc6ec03fc8";
  }

  static const char* value(const ::xj_robot_pnc::nav_goal&) { return value(); }
};

template<>
struct DataType< ::xj_robot_pnc::nav_goal > {
  static const char* value()
  {
    return "xj_robot_pnc/nav_goal";
  }

  static const char* value(const ::xj_robot_pnc::nav_goal&) { return value(); }
};


// service_traits::MD5Sum< ::xj_robot_pnc::nav_goalRequest> should match
// service_traits::MD5Sum< ::xj_robot_pnc::nav_goal >
template<>
struct MD5Sum< ::xj_robot_pnc::nav_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::nav_goal >::value();
  }
  static const char* value(const ::xj_robot_pnc::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::nav_goalRequest> should match
// service_traits::DataType< ::xj_robot_pnc::nav_goal >
template<>
struct DataType< ::xj_robot_pnc::nav_goalRequest>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::nav_goal >::value();
  }
  static const char* value(const ::xj_robot_pnc::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xj_robot_pnc::nav_goalResponse> should match
// service_traits::MD5Sum< ::xj_robot_pnc::nav_goal >
template<>
struct MD5Sum< ::xj_robot_pnc::nav_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::nav_goal >::value();
  }
  static const char* value(const ::xj_robot_pnc::nav_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::nav_goalResponse> should match
// service_traits::DataType< ::xj_robot_pnc::nav_goal >
template<>
struct DataType< ::xj_robot_pnc::nav_goalResponse>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::nav_goal >::value();
  }
  static const char* value(const ::xj_robot_pnc::nav_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_NAV_GOAL_H
