// Generated by gencpp from file xj_robot_pnc/record_stop.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_RECORD_STOP_H
#define XJ_ROBOT_PNC_MESSAGE_RECORD_STOP_H

#include <ros/service_traits.h>


#include <xj_robot_pnc/record_stopRequest.h>
#include <xj_robot_pnc/record_stopResponse.h>


namespace xj_robot_pnc
{

struct record_stop
{

typedef record_stopRequest Request;
typedef record_stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct record_stop
} // namespace xj_robot_pnc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xj_robot_pnc::record_stop > {
  static const char* value()
  {
    return "a25665d7f9b3b7071ad230c72b69fe34";
  }

  static const char* value(const ::xj_robot_pnc::record_stop&) { return value(); }
};

template<>
struct DataType< ::xj_robot_pnc::record_stop > {
  static const char* value()
  {
    return "xj_robot_pnc/record_stop";
  }

  static const char* value(const ::xj_robot_pnc::record_stop&) { return value(); }
};


// service_traits::MD5Sum< ::xj_robot_pnc::record_stopRequest> should match
// service_traits::MD5Sum< ::xj_robot_pnc::record_stop >
template<>
struct MD5Sum< ::xj_robot_pnc::record_stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::record_stop >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::record_stopRequest> should match
// service_traits::DataType< ::xj_robot_pnc::record_stop >
template<>
struct DataType< ::xj_robot_pnc::record_stopRequest>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::record_stop >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xj_robot_pnc::record_stopResponse> should match
// service_traits::MD5Sum< ::xj_robot_pnc::record_stop >
template<>
struct MD5Sum< ::xj_robot_pnc::record_stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::record_stop >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::record_stopResponse> should match
// service_traits::DataType< ::xj_robot_pnc::record_stop >
template<>
struct DataType< ::xj_robot_pnc::record_stopResponse>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::record_stop >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_RECORD_STOP_H
