// Generated by gencpp from file xj_robot_pnc/record_startRequest.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_RECORD_STARTREQUEST_H
#define XJ_ROBOT_PNC_MESSAGE_RECORD_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xj_robot_pnc
{
template <class ContainerAllocator>
struct record_startRequest_
{
  typedef record_startRequest_<ContainerAllocator> Type;

  record_startRequest_()
    : path_name()
    , dir()  {
    }
  record_startRequest_(const ContainerAllocator& _alloc)
    : path_name(_alloc)
    , dir(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_name_type;
  _path_name_type path_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> const> ConstPtr;

}; // struct record_startRequest_

typedef ::xj_robot_pnc::record_startRequest_<std::allocator<void> > record_startRequest;

typedef boost::shared_ptr< ::xj_robot_pnc::record_startRequest > record_startRequestPtr;
typedef boost::shared_ptr< ::xj_robot_pnc::record_startRequest const> record_startRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xj_robot_pnc::record_startRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xj_robot_pnc::record_startRequest_<ContainerAllocator1> & lhs, const ::xj_robot_pnc::record_startRequest_<ContainerAllocator2> & rhs)
{
  return lhs.path_name == rhs.path_name &&
    lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xj_robot_pnc::record_startRequest_<ContainerAllocator1> & lhs, const ::xj_robot_pnc::record_startRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xj_robot_pnc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "853c1a2c5795307b1ef04252400b960e";
  }

  static const char* value(const ::xj_robot_pnc::record_startRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x853c1a2c5795307bULL;
  static const uint64_t static_value2 = 0x1ef04252400b960eULL;
};

template<class ContainerAllocator>
struct DataType< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xj_robot_pnc/record_startRequest";
  }

  static const char* value(const ::xj_robot_pnc::record_startRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path_name\n"
"string dir\n"
;
  }

  static const char* value(const ::xj_robot_pnc::record_startRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path_name);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_startRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xj_robot_pnc::record_startRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xj_robot_pnc::record_startRequest_<ContainerAllocator>& v)
  {
    s << indent << "path_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path_name);
    s << indent << "dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_RECORD_STARTREQUEST_H
