// Generated by gencpp from file xj_robot_pnc/record_start.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_RECORD_START_H
#define XJ_ROBOT_PNC_MESSAGE_RECORD_START_H

#include <ros/service_traits.h>


#include <xj_robot_pnc/record_startRequest.h>
#include <xj_robot_pnc/record_startResponse.h>


namespace xj_robot_pnc
{

struct record_start
{

typedef record_startRequest Request;
typedef record_startResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct record_start
} // namespace xj_robot_pnc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xj_robot_pnc::record_start > {
  static const char* value()
  {
    return "1ec11de8b8f99b8a7fdec75970d60c52";
  }

  static const char* value(const ::xj_robot_pnc::record_start&) { return value(); }
};

template<>
struct DataType< ::xj_robot_pnc::record_start > {
  static const char* value()
  {
    return "xj_robot_pnc/record_start";
  }

  static const char* value(const ::xj_robot_pnc::record_start&) { return value(); }
};


// service_traits::MD5Sum< ::xj_robot_pnc::record_startRequest> should match
// service_traits::MD5Sum< ::xj_robot_pnc::record_start >
template<>
struct MD5Sum< ::xj_robot_pnc::record_startRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::record_start >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_startRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::record_startRequest> should match
// service_traits::DataType< ::xj_robot_pnc::record_start >
template<>
struct DataType< ::xj_robot_pnc::record_startRequest>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::record_start >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_startRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xj_robot_pnc::record_startResponse> should match
// service_traits::MD5Sum< ::xj_robot_pnc::record_start >
template<>
struct MD5Sum< ::xj_robot_pnc::record_startResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::record_start >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_startResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::record_startResponse> should match
// service_traits::DataType< ::xj_robot_pnc::record_start >
template<>
struct DataType< ::xj_robot_pnc::record_startResponse>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::record_start >::value();
  }
  static const char* value(const ::xj_robot_pnc::record_startResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_RECORD_START_H
