// Generated by gencpp from file xj_robot_pnc/record_stopResponse.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_RECORD_STOPRESPONSE_H
#define XJ_ROBOT_PNC_MESSAGE_RECORD_STOPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xj_robot_pnc
{
template <class ContainerAllocator>
struct record_stopResponse_
{
  typedef record_stopResponse_<ContainerAllocator> Type;

  record_stopResponse_()
    : message()  {
    }
  record_stopResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct record_stopResponse_

typedef ::xj_robot_pnc::record_stopResponse_<std::allocator<void> > record_stopResponse;

typedef boost::shared_ptr< ::xj_robot_pnc::record_stopResponse > record_stopResponsePtr;
typedef boost::shared_ptr< ::xj_robot_pnc::record_stopResponse const> record_stopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator1> & lhs, const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator1> & lhs, const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xj_robot_pnc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xj_robot_pnc/record_stopResponse";
  }

  static const char* value(const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_stopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xj_robot_pnc::record_stopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xj_robot_pnc::record_stopResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_RECORD_STOPRESPONSE_H
