// Generated by gencpp from file xj_robot_pnc/xj_robot_task.msg
// DO NOT EDIT!


#ifndef XJ_ROBOT_PNC_MESSAGE_XJ_ROBOT_TASK_H
#define XJ_ROBOT_PNC_MESSAGE_XJ_ROBOT_TASK_H

#include <ros/service_traits.h>


#include <xj_robot_pnc/xj_robot_taskRequest.h>
#include <xj_robot_pnc/xj_robot_taskResponse.h>


namespace xj_robot_pnc
{

struct xj_robot_task
{

typedef xj_robot_taskRequest Request;
typedef xj_robot_taskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct xj_robot_task
} // namespace xj_robot_pnc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xj_robot_pnc::xj_robot_task > {
  static const char* value()
  {
    return "347eea49e7b11fe6ce7ff80abc574c91";
  }

  static const char* value(const ::xj_robot_pnc::xj_robot_task&) { return value(); }
};

template<>
struct DataType< ::xj_robot_pnc::xj_robot_task > {
  static const char* value()
  {
    return "xj_robot_pnc/xj_robot_task";
  }

  static const char* value(const ::xj_robot_pnc::xj_robot_task&) { return value(); }
};


// service_traits::MD5Sum< ::xj_robot_pnc::xj_robot_taskRequest> should match
// service_traits::MD5Sum< ::xj_robot_pnc::xj_robot_task >
template<>
struct MD5Sum< ::xj_robot_pnc::xj_robot_taskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::xj_robot_task >::value();
  }
  static const char* value(const ::xj_robot_pnc::xj_robot_taskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::xj_robot_taskRequest> should match
// service_traits::DataType< ::xj_robot_pnc::xj_robot_task >
template<>
struct DataType< ::xj_robot_pnc::xj_robot_taskRequest>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::xj_robot_task >::value();
  }
  static const char* value(const ::xj_robot_pnc::xj_robot_taskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xj_robot_pnc::xj_robot_taskResponse> should match
// service_traits::MD5Sum< ::xj_robot_pnc::xj_robot_task >
template<>
struct MD5Sum< ::xj_robot_pnc::xj_robot_taskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xj_robot_pnc::xj_robot_task >::value();
  }
  static const char* value(const ::xj_robot_pnc::xj_robot_taskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xj_robot_pnc::xj_robot_taskResponse> should match
// service_traits::DataType< ::xj_robot_pnc::xj_robot_task >
template<>
struct DataType< ::xj_robot_pnc::xj_robot_taskResponse>
{
  static const char* value()
  {
    return DataType< ::xj_robot_pnc::xj_robot_task >::value();
  }
  static const char* value(const ::xj_robot_pnc::xj_robot_taskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XJ_ROBOT_PNC_MESSAGE_XJ_ROBOT_TASK_H
