// Generated by gencpp from file srvbg/bed_recogResponse.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_BED_RECOGRESPONSE_H
#define SRVBG_MESSAGE_BED_RECOGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvbg
{
template <class ContainerAllocator>
struct bed_recogResponse_
{
  typedef bed_recogResponse_<ContainerAllocator> Type;

  bed_recogResponse_()
    : have_people(false)  {
    }
  bed_recogResponse_(const ContainerAllocator& _alloc)
    : have_people(false)  {
  (void)_alloc;
    }



   typedef uint8_t _have_people_type;
  _have_people_type have_people;





  typedef boost::shared_ptr< ::srvbg::bed_recogResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvbg::bed_recogResponse_<ContainerAllocator> const> ConstPtr;

}; // struct bed_recogResponse_

typedef ::srvbg::bed_recogResponse_<std::allocator<void> > bed_recogResponse;

typedef boost::shared_ptr< ::srvbg::bed_recogResponse > bed_recogResponsePtr;
typedef boost::shared_ptr< ::srvbg::bed_recogResponse const> bed_recogResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvbg::bed_recogResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvbg::bed_recogResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srvbg::bed_recogResponse_<ContainerAllocator1> & lhs, const ::srvbg::bed_recogResponse_<ContainerAllocator2> & rhs)
{
  return lhs.have_people == rhs.have_people;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srvbg::bed_recogResponse_<ContainerAllocator1> & lhs, const ::srvbg::bed_recogResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srvbg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srvbg::bed_recogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvbg::bed_recogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::bed_recogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::bed_recogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::bed_recogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::bed_recogResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvbg::bed_recogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c9541b38c0622b3de056b9ecccd85e6";
  }

  static const char* value(const ::srvbg::bed_recogResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c9541b38c0622b3ULL;
  static const uint64_t static_value2 = 0xde056b9ecccd85e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::srvbg::bed_recogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvbg/bed_recogResponse";
  }

  static const char* value(const ::srvbg::bed_recogResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvbg::bed_recogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool have_people\n"
"\n"
"\n"
"\n"
"##病床识别节点提供服务\n"
"##发送送一次，识别一次。\n"
"##不发送请求，则不进行识别。\n"
"##start_recog_bed数值无所谓\n"
"##返回have_people数值代表识别有无人。\n"
"##需要等待服务结束才能进行接下来的业务\n"
;
  }

  static const char* value(const ::srvbg::bed_recogResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvbg::bed_recogResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.have_people);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bed_recogResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvbg::bed_recogResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srvbg::bed_recogResponse_<ContainerAllocator>& v)
  {
    s << indent << "have_people: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.have_people);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRVBG_MESSAGE_BED_RECOGRESPONSE_H
