// Generated by gencpp from file srvbg/face_recogRequest.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_FACE_RECOGREQUEST_H
#define SRVBG_MESSAGE_FACE_RECOGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvbg
{
template <class ContainerAllocator>
struct face_recogRequest_
{
  typedef face_recogRequest_<ContainerAllocator> Type;

  face_recogRequest_()
    : start_face_recog(false)  {
    }
  face_recogRequest_(const ContainerAllocator& _alloc)
    : start_face_recog(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_face_recog_type;
  _start_face_recog_type start_face_recog;





  typedef boost::shared_ptr< ::srvbg::face_recogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvbg::face_recogRequest_<ContainerAllocator> const> ConstPtr;

}; // struct face_recogRequest_

typedef ::srvbg::face_recogRequest_<std::allocator<void> > face_recogRequest;

typedef boost::shared_ptr< ::srvbg::face_recogRequest > face_recogRequestPtr;
typedef boost::shared_ptr< ::srvbg::face_recogRequest const> face_recogRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvbg::face_recogRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvbg::face_recogRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srvbg::face_recogRequest_<ContainerAllocator1> & lhs, const ::srvbg::face_recogRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_face_recog == rhs.start_face_recog;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srvbg::face_recogRequest_<ContainerAllocator1> & lhs, const ::srvbg::face_recogRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srvbg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srvbg::face_recogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvbg::face_recogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::face_recogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::face_recogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::face_recogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::face_recogRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvbg::face_recogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9a47b3cff5f3f6559ed7149c5211449";
  }

  static const char* value(const ::srvbg::face_recogRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9a47b3cff5f3f65ULL;
  static const uint64_t static_value2 = 0x59ed7149c5211449ULL;
};

template<class ContainerAllocator>
struct DataType< ::srvbg::face_recogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvbg/face_recogRequest";
  }

  static const char* value(const ::srvbg::face_recogRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvbg::face_recogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_face_recog\n"
;
  }

  static const char* value(const ::srvbg::face_recogRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvbg::face_recogRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_face_recog);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct face_recogRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvbg::face_recogRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srvbg::face_recogRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_face_recog: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_face_recog);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRVBG_MESSAGE_FACE_RECOGREQUEST_H
