// Generated by gencpp from file srvbg/face_recog.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_FACE_RECOG_H
#define SRVBG_MESSAGE_FACE_RECOG_H

#include <ros/service_traits.h>


#include <srvbg/face_recogRequest.h>
#include <srvbg/face_recogResponse.h>


namespace srvbg
{

struct face_recog
{

typedef face_recogRequest Request;
typedef face_recogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct face_recog
} // namespace srvbg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvbg::face_recog > {
  static const char* value()
  {
    return "c4eb8bf02b945647ede55dad5ed70f85";
  }

  static const char* value(const ::srvbg::face_recog&) { return value(); }
};

template<>
struct DataType< ::srvbg::face_recog > {
  static const char* value()
  {
    return "srvbg/face_recog";
  }

  static const char* value(const ::srvbg::face_recog&) { return value(); }
};


// service_traits::MD5Sum< ::srvbg::face_recogRequest> should match
// service_traits::MD5Sum< ::srvbg::face_recog >
template<>
struct MD5Sum< ::srvbg::face_recogRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::face_recog >::value();
  }
  static const char* value(const ::srvbg::face_recogRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::face_recogRequest> should match
// service_traits::DataType< ::srvbg::face_recog >
template<>
struct DataType< ::srvbg::face_recogRequest>
{
  static const char* value()
  {
    return DataType< ::srvbg::face_recog >::value();
  }
  static const char* value(const ::srvbg::face_recogRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvbg::face_recogResponse> should match
// service_traits::MD5Sum< ::srvbg::face_recog >
template<>
struct MD5Sum< ::srvbg::face_recogResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::face_recog >::value();
  }
  static const char* value(const ::srvbg::face_recogResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::face_recogResponse> should match
// service_traits::DataType< ::srvbg::face_recog >
template<>
struct DataType< ::srvbg::face_recogResponse>
{
  static const char* value()
  {
    return DataType< ::srvbg::face_recog >::value();
  }
  static const char* value(const ::srvbg::face_recogResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVBG_MESSAGE_FACE_RECOG_H
