// Generated by gencpp from file srvbg/face_recogResponse.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_FACE_RECOGRESPONSE_H
#define SRVBG_MESSAGE_FACE_RECOGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvbg
{
template <class ContainerAllocator>
struct face_recogResponse_
{
  typedef face_recogResponse_<ContainerAllocator> Type;

  face_recogResponse_()
    : people_id(0)  {
    }
  face_recogResponse_(const ContainerAllocator& _alloc)
    : people_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _people_id_type;
  _people_id_type people_id;





  typedef boost::shared_ptr< ::srvbg::face_recogResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvbg::face_recogResponse_<ContainerAllocator> const> ConstPtr;

}; // struct face_recogResponse_

typedef ::srvbg::face_recogResponse_<std::allocator<void> > face_recogResponse;

typedef boost::shared_ptr< ::srvbg::face_recogResponse > face_recogResponsePtr;
typedef boost::shared_ptr< ::srvbg::face_recogResponse const> face_recogResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvbg::face_recogResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvbg::face_recogResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srvbg::face_recogResponse_<ContainerAllocator1> & lhs, const ::srvbg::face_recogResponse_<ContainerAllocator2> & rhs)
{
  return lhs.people_id == rhs.people_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srvbg::face_recogResponse_<ContainerAllocator1> & lhs, const ::srvbg::face_recogResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srvbg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srvbg::face_recogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvbg::face_recogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::face_recogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::face_recogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::face_recogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::face_recogResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvbg::face_recogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c9e6726201cbf6822a62cbfd44572e4";
  }

  static const char* value(const ::srvbg::face_recogResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c9e6726201cbf68ULL;
  static const uint64_t static_value2 = 0x22a62cbfd44572e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::srvbg::face_recogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvbg/face_recogResponse";
  }

  static const char* value(const ::srvbg::face_recogResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvbg::face_recogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 people_id\n"
"\n"
"##人脸识别节点提供服务\n"
"##发送送一次，识别到对象为止。\n"
"##不发送请求，则不进行识别。\n"
"##start_face_recog数值无所谓\n"
"##返回people_id数值代表识别到的病人id。\n"
"##需要等待服务结束才能进行接下来的业务\n"
;
  }

  static const char* value(const ::srvbg::face_recogResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvbg::face_recogResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.people_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct face_recogResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvbg::face_recogResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srvbg::face_recogResponse_<ContainerAllocator>& v)
  {
    s << indent << "people_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.people_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRVBG_MESSAGE_FACE_RECOGRESPONSE_H
