// Generated by gencpp from file srvbg/nav_goal.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_NAV_GOAL_H
#define SRVBG_MESSAGE_NAV_GOAL_H

#include <ros/service_traits.h>


#include <srvbg/nav_goalRequest.h>
#include <srvbg/nav_goalResponse.h>


namespace srvbg
{

struct nav_goal
{

typedef nav_goalRequest Request;
typedef nav_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_goal
} // namespace srvbg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvbg::nav_goal > {
  static const char* value()
  {
    return "5776176c95d37b90d51191fc6ec03fc8";
  }

  static const char* value(const ::srvbg::nav_goal&) { return value(); }
};

template<>
struct DataType< ::srvbg::nav_goal > {
  static const char* value()
  {
    return "srvbg/nav_goal";
  }

  static const char* value(const ::srvbg::nav_goal&) { return value(); }
};


// service_traits::MD5Sum< ::srvbg::nav_goalRequest> should match
// service_traits::MD5Sum< ::srvbg::nav_goal >
template<>
struct MD5Sum< ::srvbg::nav_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::nav_goal >::value();
  }
  static const char* value(const ::srvbg::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::nav_goalRequest> should match
// service_traits::DataType< ::srvbg::nav_goal >
template<>
struct DataType< ::srvbg::nav_goalRequest>
{
  static const char* value()
  {
    return DataType< ::srvbg::nav_goal >::value();
  }
  static const char* value(const ::srvbg::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvbg::nav_goalResponse> should match
// service_traits::MD5Sum< ::srvbg::nav_goal >
template<>
struct MD5Sum< ::srvbg::nav_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::nav_goal >::value();
  }
  static const char* value(const ::srvbg::nav_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::nav_goalResponse> should match
// service_traits::DataType< ::srvbg::nav_goal >
template<>
struct DataType< ::srvbg::nav_goalResponse>
{
  static const char* value()
  {
    return DataType< ::srvbg::nav_goal >::value();
  }
  static const char* value(const ::srvbg::nav_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVBG_MESSAGE_NAV_GOAL_H
