// Generated by gencpp from file srvbg/people_id_uiResponse.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_PEOPLE_ID_UIRESPONSE_H
#define SRVBG_MESSAGE_PEOPLE_ID_UIRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvbg
{
template <class ContainerAllocator>
struct people_id_uiResponse_
{
  typedef people_id_uiResponse_<ContainerAllocator> Type;

  people_id_uiResponse_()
    : get_ok(false)  {
    }
  people_id_uiResponse_(const ContainerAllocator& _alloc)
    : get_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _get_ok_type;
  _get_ok_type get_ok;





  typedef boost::shared_ptr< ::srvbg::people_id_uiResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvbg::people_id_uiResponse_<ContainerAllocator> const> ConstPtr;

}; // struct people_id_uiResponse_

typedef ::srvbg::people_id_uiResponse_<std::allocator<void> > people_id_uiResponse;

typedef boost::shared_ptr< ::srvbg::people_id_uiResponse > people_id_uiResponsePtr;
typedef boost::shared_ptr< ::srvbg::people_id_uiResponse const> people_id_uiResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvbg::people_id_uiResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvbg::people_id_uiResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srvbg::people_id_uiResponse_<ContainerAllocator1> & lhs, const ::srvbg::people_id_uiResponse_<ContainerAllocator2> & rhs)
{
  return lhs.get_ok == rhs.get_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srvbg::people_id_uiResponse_<ContainerAllocator1> & lhs, const ::srvbg::people_id_uiResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srvbg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvbg::people_id_uiResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::people_id_uiResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::people_id_uiResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4def4bf2b1517ba03b6a5bb49ad0019f";
  }

  static const char* value(const ::srvbg::people_id_uiResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4def4bf2b1517ba0ULL;
  static const uint64_t static_value2 = 0x3b6a5bb49ad0019fULL;
};

template<class ContainerAllocator>
struct DataType< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvbg/people_id_uiResponse";
  }

  static const char* value(const ::srvbg::people_id_uiResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool get_ok\n"
"\n"
"##发送病人id信息\n"
"##提供服务端接受到people_id后，马上返回get_ok。\n"
;
  }

  static const char* value(const ::srvbg::people_id_uiResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct people_id_uiResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvbg::people_id_uiResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srvbg::people_id_uiResponse_<ContainerAllocator>& v)
  {
    s << indent << "get_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRVBG_MESSAGE_PEOPLE_ID_UIRESPONSE_H
