// Generated by gencpp from file srvbg/people_id_lan.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_PEOPLE_ID_LAN_H
#define SRVBG_MESSAGE_PEOPLE_ID_LAN_H

#include <ros/service_traits.h>


#include <srvbg/people_id_lanRequest.h>
#include <srvbg/people_id_lanResponse.h>


namespace srvbg
{

struct people_id_lan
{

typedef people_id_lanRequest Request;
typedef people_id_lanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct people_id_lan
} // namespace srvbg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvbg::people_id_lan > {
  static const char* value()
  {
    return "4c24b88bb7a19a8415013642d1cfd801";
  }

  static const char* value(const ::srvbg::people_id_lan&) { return value(); }
};

template<>
struct DataType< ::srvbg::people_id_lan > {
  static const char* value()
  {
    return "srvbg/people_id_lan";
  }

  static const char* value(const ::srvbg::people_id_lan&) { return value(); }
};


// service_traits::MD5Sum< ::srvbg::people_id_lanRequest> should match
// service_traits::MD5Sum< ::srvbg::people_id_lan >
template<>
struct MD5Sum< ::srvbg::people_id_lanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::people_id_lan >::value();
  }
  static const char* value(const ::srvbg::people_id_lanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::people_id_lanRequest> should match
// service_traits::DataType< ::srvbg::people_id_lan >
template<>
struct DataType< ::srvbg::people_id_lanRequest>
{
  static const char* value()
  {
    return DataType< ::srvbg::people_id_lan >::value();
  }
  static const char* value(const ::srvbg::people_id_lanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvbg::people_id_lanResponse> should match
// service_traits::MD5Sum< ::srvbg::people_id_lan >
template<>
struct MD5Sum< ::srvbg::people_id_lanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::people_id_lan >::value();
  }
  static const char* value(const ::srvbg::people_id_lanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::people_id_lanResponse> should match
// service_traits::DataType< ::srvbg::people_id_lan >
template<>
struct DataType< ::srvbg::people_id_lanResponse>
{
  static const char* value()
  {
    return DataType< ::srvbg::people_id_lan >::value();
  }
  static const char* value(const ::srvbg::people_id_lanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVBG_MESSAGE_PEOPLE_ID_LAN_H
