// Generated by gencpp from file srvbg/people_id_ui.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_PEOPLE_ID_UI_H
#define SRVBG_MESSAGE_PEOPLE_ID_UI_H

#include <ros/service_traits.h>


#include <srvbg/people_id_uiRequest.h>
#include <srvbg/people_id_uiResponse.h>


namespace srvbg
{

struct people_id_ui
{

typedef people_id_uiRequest Request;
typedef people_id_uiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct people_id_ui
} // namespace srvbg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvbg::people_id_ui > {
  static const char* value()
  {
    return "951a25e8f2062cf3a7d7d54a9560079a";
  }

  static const char* value(const ::srvbg::people_id_ui&) { return value(); }
};

template<>
struct DataType< ::srvbg::people_id_ui > {
  static const char* value()
  {
    return "srvbg/people_id_ui";
  }

  static const char* value(const ::srvbg::people_id_ui&) { return value(); }
};


// service_traits::MD5Sum< ::srvbg::people_id_uiRequest> should match
// service_traits::MD5Sum< ::srvbg::people_id_ui >
template<>
struct MD5Sum< ::srvbg::people_id_uiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::people_id_ui >::value();
  }
  static const char* value(const ::srvbg::people_id_uiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::people_id_uiRequest> should match
// service_traits::DataType< ::srvbg::people_id_ui >
template<>
struct DataType< ::srvbg::people_id_uiRequest>
{
  static const char* value()
  {
    return DataType< ::srvbg::people_id_ui >::value();
  }
  static const char* value(const ::srvbg::people_id_uiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvbg::people_id_uiResponse> should match
// service_traits::MD5Sum< ::srvbg::people_id_ui >
template<>
struct MD5Sum< ::srvbg::people_id_uiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::people_id_ui >::value();
  }
  static const char* value(const ::srvbg::people_id_uiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::people_id_uiResponse> should match
// service_traits::DataType< ::srvbg::people_id_ui >
template<>
struct DataType< ::srvbg::people_id_uiResponse>
{
  static const char* value()
  {
    return DataType< ::srvbg::people_id_ui >::value();
  }
  static const char* value(const ::srvbg::people_id_uiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVBG_MESSAGE_PEOPLE_ID_UI_H
