// Generated by gencpp from file srvbg/recept_start.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_RECEPT_START_H
#define SRVBG_MESSAGE_RECEPT_START_H

#include <ros/service_traits.h>


#include <srvbg/recept_startRequest.h>
#include <srvbg/recept_startResponse.h>


namespace srvbg
{

struct recept_start
{

typedef recept_startRequest Request;
typedef recept_startResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct recept_start
} // namespace srvbg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvbg::recept_start > {
  static const char* value()
  {
    return "01e466c8eb71ba7ac0b6740b7da30b81";
  }

  static const char* value(const ::srvbg::recept_start&) { return value(); }
};

template<>
struct DataType< ::srvbg::recept_start > {
  static const char* value()
  {
    return "srvbg/recept_start";
  }

  static const char* value(const ::srvbg::recept_start&) { return value(); }
};


// service_traits::MD5Sum< ::srvbg::recept_startRequest> should match
// service_traits::MD5Sum< ::srvbg::recept_start >
template<>
struct MD5Sum< ::srvbg::recept_startRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::recept_start >::value();
  }
  static const char* value(const ::srvbg::recept_startRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::recept_startRequest> should match
// service_traits::DataType< ::srvbg::recept_start >
template<>
struct DataType< ::srvbg::recept_startRequest>
{
  static const char* value()
  {
    return DataType< ::srvbg::recept_start >::value();
  }
  static const char* value(const ::srvbg::recept_startRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvbg::recept_startResponse> should match
// service_traits::MD5Sum< ::srvbg::recept_start >
template<>
struct MD5Sum< ::srvbg::recept_startResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::recept_start >::value();
  }
  static const char* value(const ::srvbg::recept_startResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::recept_startResponse> should match
// service_traits::DataType< ::srvbg::recept_start >
template<>
struct DataType< ::srvbg::recept_startResponse>
{
  static const char* value()
  {
    return DataType< ::srvbg::recept_start >::value();
  }
  static const char* value(const ::srvbg::recept_startResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVBG_MESSAGE_RECEPT_START_H
