// Generated by gencpp from file srvbg/visite_start.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_VISITE_START_H
#define SRVBG_MESSAGE_VISITE_START_H

#include <ros/service_traits.h>


#include <srvbg/visite_startRequest.h>
#include <srvbg/visite_startResponse.h>


namespace srvbg
{

struct visite_start
{

typedef visite_startRequest Request;
typedef visite_startResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visite_start
} // namespace srvbg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvbg::visite_start > {
  static const char* value()
  {
    return "3a3696aff47d8afac6800c82253e3809";
  }

  static const char* value(const ::srvbg::visite_start&) { return value(); }
};

template<>
struct DataType< ::srvbg::visite_start > {
  static const char* value()
  {
    return "srvbg/visite_start";
  }

  static const char* value(const ::srvbg::visite_start&) { return value(); }
};


// service_traits::MD5Sum< ::srvbg::visite_startRequest> should match
// service_traits::MD5Sum< ::srvbg::visite_start >
template<>
struct MD5Sum< ::srvbg::visite_startRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::visite_start >::value();
  }
  static const char* value(const ::srvbg::visite_startRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::visite_startRequest> should match
// service_traits::DataType< ::srvbg::visite_start >
template<>
struct DataType< ::srvbg::visite_startRequest>
{
  static const char* value()
  {
    return DataType< ::srvbg::visite_start >::value();
  }
  static const char* value(const ::srvbg::visite_startRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvbg::visite_startResponse> should match
// service_traits::MD5Sum< ::srvbg::visite_start >
template<>
struct MD5Sum< ::srvbg::visite_startResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvbg::visite_start >::value();
  }
  static const char* value(const ::srvbg::visite_startResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvbg::visite_startResponse> should match
// service_traits::DataType< ::srvbg::visite_start >
template<>
struct DataType< ::srvbg::visite_startResponse>
{
  static const char* value()
  {
    return DataType< ::srvbg::visite_start >::value();
  }
  static const char* value(const ::srvbg::visite_startResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVBG_MESSAGE_VISITE_START_H
