// Generated by gencpp from file srvbg/visite_startRequest.msg
// DO NOT EDIT!


#ifndef SRVBG_MESSAGE_VISITE_STARTREQUEST_H
#define SRVBG_MESSAGE_VISITE_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvbg
{
template <class ContainerAllocator>
struct visite_startRequest_
{
  typedef visite_startRequest_<ContainerAllocator> Type;

  visite_startRequest_()
    : start_visit(false)  {
    }
  visite_startRequest_(const ContainerAllocator& _alloc)
    : start_visit(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_visit_type;
  _start_visit_type start_visit;





  typedef boost::shared_ptr< ::srvbg::visite_startRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvbg::visite_startRequest_<ContainerAllocator> const> ConstPtr;

}; // struct visite_startRequest_

typedef ::srvbg::visite_startRequest_<std::allocator<void> > visite_startRequest;

typedef boost::shared_ptr< ::srvbg::visite_startRequest > visite_startRequestPtr;
typedef boost::shared_ptr< ::srvbg::visite_startRequest const> visite_startRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvbg::visite_startRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvbg::visite_startRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srvbg::visite_startRequest_<ContainerAllocator1> & lhs, const ::srvbg::visite_startRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_visit == rhs.start_visit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srvbg::visite_startRequest_<ContainerAllocator1> & lhs, const ::srvbg::visite_startRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srvbg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srvbg::visite_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvbg::visite_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::visite_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvbg::visite_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::visite_startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvbg::visite_startRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvbg::visite_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "223123a66209a82206e724a188ba4cc5";
  }

  static const char* value(const ::srvbg::visite_startRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x223123a66209a822ULL;
  static const uint64_t static_value2 = 0x06e724a188ba4cc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::srvbg::visite_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvbg/visite_startRequest";
  }

  static const char* value(const ::srvbg::visite_startRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvbg::visite_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_visit\n"
;
  }

  static const char* value(const ::srvbg::visite_startRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvbg::visite_startRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_visit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visite_startRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvbg::visite_startRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srvbg::visite_startRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_visit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_visit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRVBG_MESSAGE_VISITE_STARTREQUEST_H
